In [2]:
### Empezamos importando todo

%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np

import sys
sys.path.append('../')
import src.funciones as f

import warnings
warnings.filterwarnings('ignore')
pd.options.display.float_format = '{:.2f}'.format
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_excel('datos/BASE RT- EMBAJADORES - PRUEBA.xlsx')

Anotaciones: 
- 47 filas y 32 columnas
- 1 variable fecha, 8 decimales y 23 texto

In [4]:
df

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,Motivo de inconformidad con Titan,¿Probó fundas Titan durante la visita?,Cantidad de fundas dejadas para prueba,Resultado de prueba en obra,Comentarios técnicos / percepción del maestro,¿Aceptó volver a probar Titan?,¿Se registró en Conéctate Maestro?,¿Se aplicó bono?,Fecha de redención de bono,# de fundas compradas luego del abordaje,¿Ha influenciado a otro maestro?,Nombre del maestro influenciado,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
0,2025-04-01,PRIMERA VISITA,HAINA,ROBERT PEÑA,YANIRIS,Amauris Pichardo,8292757981.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,10.00,POSITIVO,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,RENDIMIENTO,SI,FERRETERIA FAUSTO,NaN,SI,18.41,-70.03
1,2025-04-03,PRIMERA VISITA,HAINA,FREDDY PEREZ,YANIRIS,Amauris Pichardo,8297866997.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,SI,18.42,-70.03
2,2025-05-02,PRIMERA VISITA,HAINA,ANTONIO CASTILLO,YANIRIS,Amauris Pichardo,8297854594.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,3.00,POSITIVO,NaN,NaN,SI,NaN,NaN,250.00,NaN,NaN,NaN,NaN,SI,COLOR,SI,FERRETERIA LA HACIENDA,NaN,SI,18.43,-70.02
3,2025-04-09,PRIMERA VISITA,HAINA,WASCAR PEREZ,YANIRIS,Amauris Pichardo,8099424594.00,JUAN CARLOS,IDENTIFICADO EN OBRA,DOMICEM,RESISTENCIA,SI,4.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,125.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAUSTO / AXEL,NaN,SI,18.42,-70.03
4,2025-03-15,PRIMERA VISITA,HAINA,RAFAEL PIMENTEL,YANIRIS,Amauris Pichardo,8492138214.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,10.00,NaN,NaN,NaN,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,SI,18.43,-70.02
5,2025-04-07,PRIMERA VISITA,HAINA,CANDIDO MARRERO,YANIRIS,Amauris Pichardo,8093340743.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,8.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,RESISTENCIA,NO,TEO,NaN,SI,18.43,-70.03
6,2025-04-25,PRIMERA VISITA,HAINA,JUAN FRIAS,YANIRIS,Amauris Pichardo,8297806510.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA LA HACIENDA,NaN,SI,18.43,-70.03
7,2025-05-16,PRIMERA VISITA,LOS ALCARRIZOS,FRANDELY,PAMELA,Amauris Pichardo,8496304247.00,JUAN CARLOS,REFERIDO POR COMERCIAL,CIBAO,RESISTENCIA,SI,2.00,NEUTRAL,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,COLOR,SI,FERREBEGO,NaN,SI,18.52,-70.03
8,2025-05-19,PRIMERA VISITA,LOS ALCARRIZOS,JOSE MANUEL,PAMELA,Amauris Pichardo,8095020840.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,3.00,NEUTRAL,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE LEON RIVAS,NaN,SI,18.52,-70.04
9,2025-05-19,PRIMERA VISITA,LOS ALCARRIZOS,LUCA BERNARD,PAMELA,Amauris Pichardo,NaN,JUAN CARLOS,IDENTIFICADO EN OBRA,NaN,COLOR,SI,4.00,NEUTRAL,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE LEON RIVAS,NaN,SI,18.53,-70.05
10,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,JULIAN,SURI,Ricardo Rodriguez,8297856515.00,JUAN CARLOS,REFERIDO POR COMERCIAL,SANTO DOMINGO,RESISTENCIA,SI,5.00,NEGATIVO,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,COLOR,NO,FERRETERIA CASTILLO,NaN,SI,18.84,-68.67
11,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,"JOSE CESAREO ""PAJARITO""",SURI,Ricardo Rodriguez,8095149545.00,JUAN CARLOS,REFERIDO POR COMERCIAL,PANAM,COLOR,NO,NaN,NO REALIZADA,POCA RESISTENCIA,NO,NO,NO,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA CASTILLO,ADEMAS DE LA SITUACION CON EL COLOR DEL PRODUC...,SI,18.83,-68.67
12,2025-05-23,PRIMERA VISITA,SAN JUAN,VICTOR VARGAS,LUIS,Amauris Pichardo,8297644691.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,SI,5.00,POSITIVO,NaN,NaN,SI,NaN,NaN,350.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA ARSENILIA,NaN,SI,18.80,-71.23
13,2025-05-23,PRIMERA VISITA,SAN JUAN,FREDDY,LUIS,Amauris Pichardo,8096686368.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA HUMBERTO,NaN,SI,18.75,-71.19
14,2025-05-23,PRIMERA VISITA,SAN JUAN,CHAN,LUIS,Amauris Pichardo,8293270329.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,RESISTENCIA,SI,6.00,NEGATIVO,NO TIENE LA RESISTENCIA ESPERADA Y MENOR RENDI...,NO,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,SI,RENDIMIENTO,SI,FERRETERIA HUMBERTO,NaN,SI,18.75,-71.19
15,2025-04-24,PRIMERA VISITA,SABANA IGLESIA,IGNACIO RODRIGUEZ,MERCEDES,Siquio Salazar,8097617532.00,JUAN CARLOS,REFERIDO POR COMERCIAL,DOMICEM,COLOR,SI,5.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,536.00,SI,LEO,8096717580.00,50.00,NaN,NaN,NaN,CENTRO FERRETERO SABANA IGLESIA,NaN,SI,19.29,-70.74
16,2025-04-24,PRIMERA VISITA,SABANA IGLESIA,MERISIER,MERCEDES,Siquio Salazar,NaN,JUAN CARLOS,REFERIDO POR COMERCIAL,DOMICEM,RESISTENCIA,NO,NaN,NO REALIZADA,BAJO RENDIMIENTO,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,19.33,-70.76
17,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,JESUS PINEDA,RAQUEL,Amauris Pichardo,8294260508.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MARTINEZ PACHA,NaN,SI,18.55,-70.50
18,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,CRISTIAN DIAZ,RAQUEL,Amauris Pichardo,8096130285.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.54,-70.51
19,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FRANCISCO,RAQUEL,Amauris Pichardo,8292627135.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,8.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.54,-70.51
20,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FREDDY ENCARNACION,RAQUEL,Amauris Pichardo,8096538015.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.54,-70.51
21,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,LECLES ELIUS,RAQUEL,Amauris Pichardo,8094977171.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,JUAN PEREZ,NaN,15.00,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.53,-70.51
22,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FRANCIS FILOGENE,RAQUEL,Amauris Pichardo,8298919912.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,MANUEL,NaN,80.00,NaN,NaN,NaN,FERNANDEZ,NaN,SI,18.55,-70.51
23,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FERNANDO PETTER,RAQUEL,Amauris Pichardo,8296335597.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,IVAN,NaN,125.00,NaN,NaN,NaN,FERRETERIA JUANA,NaN,SI,18.54,-70.51
24,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,PITTER ABERA,RAQUEL,Amauris Pichardo,8494927897.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,CRISTIAN,NaN,85.00,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.59,-70.50
25,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,JESUS PINEDA,RAQUEL,Amauris Pichardo,8294260508.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,10.00,SI,JOSE,NaN,60.00,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
26,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,CRISTIAN DIAZ,RAQUEL,Amauris Pichardo,8096130285.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,4.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
27,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FRANCISCO,RAQUEL,Amauris Pichardo,8292627135.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,4.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
28,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FREDDY ENCARNACION,RAQUEL,Amauris Pichardo,8096538015.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
29,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,LECLESES ELIUS,RAQUEL,Amauris Pichardo,8094977171.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,8.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
30,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FERNANDO PETTER,RAQUEL,Amauris Pichardo,8298919912.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
31,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FRANCIS FILOGENE,RAQUEL,Amauris Pichardo,8296335597.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
32,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,PITTER ABERA,RAQUEL,Amauris Pichardo,8494927897.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
33,2025-04-08,SEGUIMIENTO,HAINA,ANTONIO CASTILLO,YANIRIS,Amauris Pichardo,8297854594.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
34,2025-04-15,SEGUIMIENTO,HAINA,RAFAEL PIMENTEL,YANIRIS,Amauris Pichardo,8492138214.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,4.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
35,2025-06-27,PRIMERA VISITA,HAINA,DARIO JIMENEZ,YANIRIS,Amauris Pichardo,8099530357.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,9.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.41,-70.04
36,2025-06-27,PRIMERA VISITA,HAINA,RAMON ALVAREZ,YANIRIS,Amauris Pichardo,8292974492.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA LA HACIENDA,NaN,NO,18.42,-70.04
37,2025-06-27,PRIMERA VISITA,HAINA,WLIKIN DE OLEO,YANIRIS,Amauris Pichardo,8093996275.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.41,-70.04
38,2025-06-27,PRIMERA VISITA,HAINA,ROBERTO JAVIER,YANIRIS,Amauris Pichardo,8098618672.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.41,-70.03
39,2025-04-26,PRIMERA VISITA,AZUA,WILLIAM MEDRANO,RAQUEL,Amauris Pichardo,8097102794.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,NO,NaN,NaN,POCA RESISTENCIA,NaN,SI,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.45,-70.75
40,2025-04-26,PRIMERA VISITA,AZUA,ESQUIA ARVELO,RAQUEL,Amauris Pichardo,8292090022.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,NO,NaN,NaN,BAJO RENDIMIENTO,NaN,SI,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.46,-70.73
41,2025-04-26,PRIMERA VISITA,AZUA,WILLY URBAEZ,RAQUEL,Amauris Pichardo,8292940281.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,NO,NaN,NaN,MAL COLOR,NaN,SI,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.46,-70.75
42,2025-04-26,PRIMERA VISITA,AZUA,JOSE MANUEL,RAQUEL,Amauris Pichardo,8292165217.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.44,-70.73
43,2025-04-26,PRIMERA VISITA,AZUA,RADAMES ORTIZ,RAQUEL,Amauris Pichardo,8096759701.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.45,-70.71
44,2025-04-26,PRIMERA VISITA,AZUA,NICOLAS ROSARIO,RAQUEL,Amauris Pichardo,8292964226.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,NEUTRAL,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.46,-70.73
45,2025-04-26,PRIMERA VISITA,AZUA,RAFAEL MERO,RAQUEL,Amauris Pichardo,8494239611.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.44,-70.74
46,2025-04-26,PRIMERA VISITA,AZUA,JOSE DEL CARMEN,RAQUEL,Amauris Pichardo,NaN,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.45,-70.75

In [5]:
df["# de fundas compradas luego del abordaje"].sum()

1281.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 32 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Fecha                                             47 non-null     datetime64[ns]
 1   Acción realizada                                  47 non-null     object
 2   Zona / Localidad                                  47 non-null     object
 3   Nombre del maestro                                47 non-null     object
 4   Nombre del comercial                              47 non-null     object
 5   Nombre del Asesor                                 47 non-null     object
 6   Teléfono del maestro                              44 non-null     float64
 7   Influencer / Embajador de zona                    47 non-null     object
 8   Origen del Abordaje                               47 non-null     object
 9   Marca usada al momento del abordaje               46 non-null     object
 10  Motivo de inconformidad con Titan                 47 non-null     object
 11  ¿Probó fundas Titan durante la visita?            47 non-null     object
 12  Cantidad de fundas dejadas para prueba            42 non-null     float64
 13  Resultado de prueba en obra                       41 non-null     object
 14  Comentarios técnicos / percepción del maestro     6 non-null      object
 15  ¿Aceptó volver a probar Titan?                    7 non-null      object
 16  ¿Se registró en Conéctate Maestro?                25 non-null     object
 17  ¿Se aplicó bono?                                  15 non-null     object
 18  Fecha de redención de bono                        0 non-null      float64
 19  # de fundas compradas luego del abordaje          6 non-null      float64
 20  ¿Ha influenciado a otro maestro?                  14 non-null     object
 21  Nombre del maestro influenciado                   6 non-null      object
 22  Teléfono del influenciado                         1 non-null      float64
 23  Cantidad de fundas compradas por el influenciado  6 non-null      float64
 24  ¿Reportó alguna queja?                            6 non-null      object
 25  Tipo de queja                                     6 non-null      object
 26  ¿Fue resuelta?                                    6 non-null      object
 27  Ferretería donde compra                           28 non-null     object
 28  Comentarios adicionales o sugerencias             1 non-null      object
 29  Comunicado al comercial                           45 non-null     object
 30  LAT                                               37 non-null     float64
 31  LONG                                              37 non-null     float64
dtypes: datetime64[ns](1), float64(8), object(23)
memory usage: 11.9+ KB

In [7]:
df.describe()

,Fecha,Teléfono del maestro,Cantidad de fundas dejadas para prueba,Fecha de redención de bono,# de fundas compradas luego del abordaje,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,LAT,LONG
count,47,44.00,42.00,0.00,6.00,1.00,6.00,37.00,37.00
mean,2025-05-31 05:06:22.978723328,8245535163.55,6.38,NaN,213.50,8096717580.00,69.17,18.56,-70.35
min,2025-03-15 00:00:00,8093340743.00,2.00,NaN,10.00,8096717580.00,15.00,18.41,-71.23
25%,2025-04-26 00:00:00,8096741367.75,5.00,NaN,38.75,8096717580.00,52.50,18.43,-70.73
50%,2025-05-23 00:00:00,8292849131.00,5.50,NaN,187.50,8096717580.00,70.00,18.46,-70.51
75%,2025-07-15 00:00:00,8297854594.00,9.00,NaN,325.00,8096717580.00,83.75,18.55,-70.03
max,2025-07-22 00:00:00,8496304247.00,10.00,NaN,536.00,8096717580.00,125.00,19.33,-68.67
std,NaN,136486524.37,2.21,NaN,207.18,NaN,37.07,0.22,0.55

La fecha viene desde marzo hasta el mes de julio.

In [8]:
df.nunique()

Fecha                                               18
Acción realizada                                     2
Zona / Localidad                                     7
Nombre del maestro                                  37
Nombre del comercial                                 6
Nombre del Asesor                                    3
Teléfono del maestro                                34
Influencer / Embajador de zona                       1
Origen del Abordaje                                  2
Marca usada al momento del abordaje                  5
Motivo de inconformidad con Titan                    3
¿Probó fundas Titan durante la visita?               2
Cantidad de fundas dejadas para prueba               9
Resultado de prueba en obra                          4
Comentarios técnicos / percepción del maestro        4
¿Aceptó volver a probar Titan?                       2
¿Se registró en Conéctate Maestro?                   2
¿Se aplicó bono?                                     2
Fecha de redención de bono                           0
# de fundas compradas luego del abordaje             5
¿Ha influenciado a otro maestro?                     2
Nombre del maestro influenciado                      6
Teléfono del influenciado                            1
Cantidad de fundas compradas por el influenciado     6
¿Reportó alguna queja?                               1
Tipo de queja                                        3
¿Fue resuelta?                                       2
Ferretería donde compra                             14
Comentarios adicionales o sugerencias                1
Comunicado al comercial                              2
LAT                                                 34
LONG                                                36
dtype: int64

In [9]:
df.shape

(47, 32)

In [10]:
f.exploracion_dataframe(df)

El número de datos es 47 y el de columnas es 32

 .....................

Los duplicados que tenemos en el conjunto de datos son: 0

 .....................

Los nulos que tenemos en el conjunto de datos son:

                                                  %_nulos
Teléfono del maestro                                 6.38
Marca usada al momento del abordaje                  2.13
Cantidad de fundas dejadas para prueba              10.64
Resultado de prueba en obra                         12.77
Comentarios técnicos / percepción del maestro       87.23
¿Aceptó volver a probar Titan?                      85.11
¿Se registró en Conéctate Maestro?                  46.81
¿Se aplicó bono?                                    68.09
Fecha de redención de bono                         100.00
# de fundas compradas luego del abordaje            87.23
¿Ha influenciado a otro maestro?                    70.21
Nombre del maestro influenciado                     87.23
Teléfono del influenciado                           97.87
Cantidad de fundas compradas por el influenciado    87.23
¿Reportó alguna queja?                              87.23
Tipo de queja                                       87.23
¿Fue resuelta?                                      87.23
Ferretería donde compra                             40.43
Comentarios adicionales o sugerencias               97.87
Comunicado al comercial                              4.26
LAT                                                 21.28
LONG                                                21.28

 .....................

Los tipos de las columnas son:

                                                       tipo_dato
Fecha                                             datetime64[ns]
Acción realizada                                          object
Zona / Localidad                                          object
Nombre del maestro                                        object
Nombre del comercial                                      object
Nombre del Asesor                                         object
Teléfono del maestro                                     float64
Influencer / Embajador de zona                            object
Origen del Abordaje                                       object
Marca usada al momento del abordaje                       object
Motivo de inconformidad con Titan                         object
¿Probó fundas Titan durante la visita?                    object
Cantidad de fundas dejadas para prueba                   float64
Resultado de prueba en obra                               object
Comentarios técnicos / percepción del maestro             object
¿Aceptó volver a probar Titan?                            object
¿Se registró en Conéctate Maestro?                        object
¿Se aplicó bono?                                          object
Fecha de redención de bono                               float64
# de fundas compradas luego del abordaje                 float64
¿Ha influenciado a otro maestro?                          object
Nombre del maestro influenciado                           object
Teléfono del influenciado                                float64
Cantidad de fundas compradas por el influenciado         float64
¿Reportó alguna queja?                                    object
Tipo de queja                                             object
¿Fue resuelta?                                            object
Ferretería donde compra                                   object
Comentarios adicionales o sugerencias                     object
Comunicado al comercial                                   object
LAT                                                      float64
LONG                                                     float64

 .....................

Los valores que tenemos para las columnas categóricas son:
La columna Acción realizada tiene los siguientes valores únicos:

                  count
Acción realizada
PRIMERA VISITA       37
SEGUIMIENTO          10

La columna Zona / Localidad tiene los siguientes valores únicos:

                    count
Zona / Localidad
SAN JOSE DE OCOA       16
HAINA                  13
AZUA                    8
LOS ALCARRIZOS          3
SAN JUAN                3
LAGUNAS DE NISIBON      2
SABANA IGLESIA          2

La columna Nombre del maestro tiene los siguientes valores únicos:

                         count
Nombre del maestro
CRISTIAN DIAZ                2
JOSE MANUEL                  2
FRANCISCO                    2
FERNANDO PETTER              2
JESUS PINEDA                 2
PITTER ABERA                 2
FRANCIS FILOGENE             2
FREDDY ENCARNACION           2
RAFAEL PIMENTEL              2
ANTONIO CASTILLO             2
WILLY URBAEZ                 1
ESQUIA ARVELO                1
RADAMES ORTIZ                1
ROBERTO JAVIER               1
WLIKIN DE OLEO               1
RAMON ALVAREZ                1
DARIO JIMENEZ                1
LECLESES ELIUS               1
NICOLAS ROSARIO              1
RAFAEL MERO                  1
WILLIAM MEDRANO              1
ROBERT PEÑA                  1
LECLES ELIUS                 1
FREDDY PEREZ                 1
MERISIER                     1
IGNACIO RODRIGUEZ            1
CHAN                         1
FREDDY                       1
VICTOR VARGAS                1
JOSE CESAREO "PAJARITO"      1
JULIAN                       1
LUCA BERNARD                 1
FRANDELY                     1
JUAN FRIAS                   1
CANDIDO MARRERO              1
WASCAR PEREZ                 1
JOSE DEL CARMEN              1

La columna Nombre del comercial tiene los siguientes valores únicos:

                      count
Nombre del comercial
RAQUEL                   24
YANIRIS                  13
PAMELA                    3
LUIS                      3
SURI                      2
MERCEDES                  2

La columna Nombre del Asesor tiene los siguientes valores únicos:

                   count
Nombre del Asesor
Amauris Pichardo      43
Ricardo Rodriguez      2
Siquio Salazar         2

La columna Influencer / Embajador de zona tiene los siguientes valores únicos:

                                count
Influencer / Embajador de zona
JUAN CARLOS                        47

La columna Origen del Abordaje tiene los siguientes valores únicos:

                        count
Origen del Abordaje
IDENTIFICADO EN OBRA       31
REFERIDO POR COMERCIAL     16

La columna Marca usada al momento del abordaje tiene los siguientes valores únicos:

                                     count
Marca usada al momento del abordaje
ARGOS                                   40
DOMICEM                                  3
CIBAO                                    1
SANTO DOMINGO                            1
PANAM                                    1

La columna Motivo de inconformidad con Titan tiene los siguientes valores únicos:

                                   count
Motivo de inconformidad con Titan
COLOR                                 32
RESISTENCIA                           10
DISPONIBILIDAD                         5

La columna ¿Probó fundas Titan durante la visita? tiene los siguientes valores únicos:

                                        count
¿Probó fundas Titan durante la visita?
SI                                         42
NO                                          5

La columna Resultado de prueba en obra tiene los siguientes valores únicos:

                             count
Resultado de prueba en obra
POSITIVO                        33
NEUTRAL                          4
NEGATIVO                         2
NO REALIZADA                     2

La columna Comentarios técnicos / percepción del maestro tiene los siguientes valores únicos:

                                                    count
Comentarios técnicos / percepción del maestro
POCA RESISTENCIA                                        2
BAJO RENDIMIENTO                                        2
NO TIENE LA RESISTENCIA ESPERADA Y MENOR RENDIM...      1
MAL COLOR                                               1

La columna ¿Aceptó volver a probar Titan? tiene los siguientes valores únicos:

                                count
¿Aceptó volver a probar Titan?
NO                                  5
SI                                  2

La columna ¿Se registró en Conéctate Maestro? tiene los siguientes valores únicos:

                                    count
¿Se registró en Conéctate Maestro?
SI                                     21
NO                                      4

La columna ¿Se aplicó bono? tiene los siguientes valores únicos:

                  count
¿Se aplicó bono?
SI                   10
NO                    5

La columna ¿Ha influenciado a otro maestro? tiene los siguientes valores únicos:

                                  count
¿Ha influenciado a otro maestro?
NO                                    8
SI                                    6

La columna Nombre del maestro influenciado tiene los siguientes valores únicos:

                                 count
Nombre del maestro influenciado
LEO                                  1
JUAN PEREZ                           1
MANUEL                               1
IVAN                                 1
CRISTIAN                             1
JOSE                                 1

La columna ¿Reportó alguna queja? tiene los siguientes valores únicos:

                        count
¿Reportó alguna queja?
SI                          6

La columna Tipo de queja tiene los siguientes valores únicos:

               count
Tipo de queja
COLOR              3
RENDIMIENTO        2
RESISTENCIA        1

La columna ¿Fue resuelta? tiene los siguientes valores únicos:

                count
¿Fue resuelta?
SI                  4
NO                  2

La columna Ferretería donde compra tiene los siguientes valores únicos:

                                 count
Ferretería donde compra
FERRETERIA FAUSTO                    6
FERREFACIL                           5
FERRETERIA LA HACIENDA               3
DE LEON RIVAS                        2
FERRETERIA CASTILLO                  2
FERRETERIA HUMBERTO                  2
FAUSTO / AXEL                        1
TEO                                  1
FERREBEGO                            1
FERRETERIA ARSENILIA                 1
CENTRO FERRETERO SABANA IGLESIA      1
MARTINEZ PACHA                       1
FERNANDEZ                            1
FERRETERIA JUANA                     1

La columna Comentarios adicionales o sugerencias tiene los siguientes valores únicos:

                                                    count
Comentarios adicionales o sugerencias
ADEMAS DE LA SITUACION CON EL COLOR DEL PRODUCT...      1

La columna Comunicado al comercial  tiene los siguientes valores únicos:

                          count
Comunicado al comercial
SI                           29
NO                           16

Tenemos: 
- 2 tipos de acciones (primera visita con 17)
- 7 localidades diferentes (San Jose de Ocoa tiene 16, le sigue Haina on 13)
- 37 nombres de maestros (varios se repiten en 2 ocasiones)
- 6 comerciales (raquel lidera con 24)
- 3 asesores (Amauris Pichardo es quien tiene más presencia 43)
- 1 influencer 
- 2 origenes de abordaje (lidera identificado en obra 31)
- 5 tipos de marcas (Argos lidera con 40)
- 3 motivos de inconformidad (lidera el color con 32)
- 42 de las ocasiones probaron el Titan durante la visita
- 33 descripciones tuvieron un resultado de prueba positivo
- 21 veces se registraron en Conéctate Maestro
- Solo en 10 ocasiones se aplicó Bono
- 6 casos reportaron quejas
- Reportaron 14 ferreterías diferentes
- 29 de comunicaron al comercial, 16 no

In [11]:
df.describe()

,Fecha,Teléfono del maestro,Cantidad de fundas dejadas para prueba,Fecha de redención de bono,# de fundas compradas luego del abordaje,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,LAT,LONG
count,47,44.00,42.00,0.00,6.00,1.00,6.00,37.00,37.00
mean,2025-05-31 05:06:22.978723328,8245535163.55,6.38,NaN,213.50,8096717580.00,69.17,18.56,-70.35
min,2025-03-15 00:00:00,8093340743.00,2.00,NaN,10.00,8096717580.00,15.00,18.41,-71.23
25%,2025-04-26 00:00:00,8096741367.75,5.00,NaN,38.75,8096717580.00,52.50,18.43,-70.73
50%,2025-05-23 00:00:00,8292849131.00,5.50,NaN,187.50,8096717580.00,70.00,18.46,-70.51
75%,2025-07-15 00:00:00,8297854594.00,9.00,NaN,325.00,8096717580.00,83.75,18.55,-70.03
max,2025-07-22 00:00:00,8496304247.00,10.00,NaN,536.00,8096717580.00,125.00,19.33,-68.67
std,NaN,136486524.37,2.21,NaN,207.18,NaN,37.07,0.22,0.55

In [12]:
df[df['Acción realizada'] == 'SEGUIMIENTO']

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,Motivo de inconformidad con Titan,¿Probó fundas Titan durante la visita?,Cantidad de fundas dejadas para prueba,Resultado de prueba en obra,Comentarios técnicos / percepción del maestro,¿Aceptó volver a probar Titan?,¿Se registró en Conéctate Maestro?,¿Se aplicó bono?,Fecha de redención de bono,# de fundas compradas luego del abordaje,¿Ha influenciado a otro maestro?,Nombre del maestro influenciado,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
25,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,JESUS PINEDA,RAQUEL,Amauris Pichardo,8294260508.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,10.00,SI,JOSE,NaN,60.00,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
26,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,CRISTIAN DIAZ,RAQUEL,Amauris Pichardo,8096130285.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,4.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
27,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FRANCISCO,RAQUEL,Amauris Pichardo,8292627135.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,4.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
28,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FREDDY ENCARNACION,RAQUEL,Amauris Pichardo,8096538015.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
29,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,LECLESES ELIUS,RAQUEL,Amauris Pichardo,8094977171.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,8.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
30,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FERNANDO PETTER,RAQUEL,Amauris Pichardo,8298919912.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
31,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FRANCIS FILOGENE,RAQUEL,Amauris Pichardo,8296335597.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
32,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,PITTER ABERA,RAQUEL,Amauris Pichardo,8494927897.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
33,2025-04-08,SEGUIMIENTO,HAINA,ANTONIO CASTILLO,YANIRIS,Amauris Pichardo,8297854594.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
34,2025-04-15,SEGUIMIENTO,HAINA,RAFAEL PIMENTEL,YANIRIS,Amauris Pichardo,8492138214.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,4.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN

In [39]:
df['Origen del Abordaje'].value_counts(normalize=True) * 100

Origen del Abordaje
IDENTIFICADO EN OBRA     65.96
REFERIDO POR COMERCIAL   34.04
Name: proportion, dtype: float64

En cuanto a las visitas de seguimiento, solo se concentran en 2 zonas: San José de Ocoa y Haina. Además, pertenecen al mismo asesor (Amauris Pichardo) y a 2 comerciales (Raquel y Yaniris).

In [13]:
df['Nombre del Asesor'].value_counts()

Nombre del Asesor
Amauris Pichardo     43
Ricardo Rodriguez     2
Siquio Salazar        2
Name: count, dtype: int64

In [15]:
df.groupby(['Nombre del Asesor', 'Acción realizada']).size().reset_index(name='frecuencias')

   Nombre del Asesor Acción realizada  frecuencias
0   Amauris Pichardo   PRIMERA VISITA           33
1   Amauris Pichardo      SEGUIMIENTO           10
2  Ricardo Rodriguez   PRIMERA VISITA            2
3     Siquio Salazar   PRIMERA VISITA            2

In [14]:
df.groupby(['Nombre del Asesor', 'Nombre del comercial']).size().reset_index(name='frecuencias')

   Nombre del Asesor Nombre del comercial  frecuencias
0   Amauris Pichardo                 LUIS            3
1   Amauris Pichardo               PAMELA            3
2   Amauris Pichardo              RAQUEL            24
3   Amauris Pichardo              YANIRIS           13
4  Ricardo Rodriguez                 SURI            2
5     Siquio Salazar             MERCEDES            2

In [35]:
df.groupby(['Nombre del Asesor', 'Nombre del comercial'])['# de fundas compradas luego del abordaje'].sum().sort_values(ascending=False)

Nombre del Asesor  Nombre del comercial
Siquio Salazar     MERCEDES               536.00
Amauris Pichardo   YANIRIS                375.00
                   LUIS                   350.00
                   RAQUEL                  20.00
                   PAMELA                   0.00
Ricardo Rodriguez  SURI                     0.00
Name: # de fundas compradas luego del abordaje, dtype: float64

Amauris trabajó con 4 comerciales, mientra que Ricardo y Siquio solo han trabajado con una respectivamente.

Amauris también ha sido el único en realizar visitas de seguimiento (San José de Ocoa y Haina)

In [36]:
df.groupby('Nombre del Asesor')['# de fundas compradas luego del abordaje'].sum().sort_values(ascending=False)

Nombre del Asesor
Amauris Pichardo    745.00
Siquio Salazar      536.00
Ricardo Rodriguez     0.00
Name: # de fundas compradas luego del abordaje, dtype: float64

In [34]:
df.groupby('Nombre del comercial')['# de fundas compradas luego del abordaje'].sum().sort_values(ascending=False)

Nombre del comercial
MERCEDES   536.00
YANIRIS    375.00
LUIS       350.00
RAQUEL      20.00
PAMELA       0.00
SURI         0.00
Name: # de fundas compradas luego del abordaje, dtype: float64

Amauris es el que tiene más cantidad de fundas compradas luego del abordaje, sin embargo Siquito solo hizo 2 visitas y no queda muy lejos.

In [38]:
df.groupby(['Nombre del Asesor', 'Zona / Localidad']).size().reset_index(name='frecuencias').sort_values(by='frecuencias', ascending=False)

   Nombre del Asesor    Zona / Localidad  frecuencias
3   Amauris Pichardo    SAN JOSE DE OCOA           16
1   Amauris Pichardo               HAINA           13
0   Amauris Pichardo                AZUA            8
2   Amauris Pichardo      LOS ALCARRIZOS            3
4   Amauris Pichardo           SAN JUAN             3
5  Ricardo Rodriguez  LAGUNAS DE NISIBON            2
6     Siquio Salazar      SABANA IGLESIA            2

In [20]:
df.groupby(['Nombre del comercial', 'Zona / Localidad']).size().reset_index(name='frecuencias').sort_values(by='frecuencias', ascending=False)

  Nombre del comercial    Zona / Localidad  frecuencias
4              RAQUEL     SAN JOSE DE OCOA           16
6              YANIRIS               HAINA           13
3              RAQUEL                 AZUA            8
0                 LUIS           SAN JUAN             3
2               PAMELA      LOS ALCARRIZOS            3
1             MERCEDES      SABANA IGLESIA            2
5                 SURI  LAGUNAS DE NISIBON            2

Las zonas que tuvieron más visitas fueron San Jose y Haina.

In [22]:
df['Marca usada al momento del abordaje'].value_counts(normalize=True) * 100

Marca usada al momento del abordaje
ARGOS           86.96
DOMICEM          6.52
CIBAO            2.17
SANTO DOMINGO    2.17
PANAM            2.17
Name: proportion, dtype: float64

In [23]:
(df['Motivo de inconformidad con Titan'].value_counts(normalize=True) * 100).round(2)

Motivo de inconformidad con Titan
COLOR            68.09
RESISTENCIA      21.28
DISPONIBILIDAD   10.64
Name: proportion, dtype: float64

In [24]:
df[df['Motivo de inconformidad con Titan'] == 'DISPONIBILIDAD']['Zona / Localidad'].value_counts()

Zona / Localidad
AZUA         4
SAN JUAN     1
Name: count, dtype: int64

In [ ]:
df.groupby('')['Ferretería donde compra'].count()

In [49]:
df.groupby('Zona / Localidad')['Ferretería donde compra'].count()

Zona / Localidad
AZUA                   0
HAINA                 11
LAGUNAS DE NISIBON     2
LOS ALCARRIZOS         3
SABANA IGLESIA         1
SAN JOSE DE OCOA       8
SAN JUAN               3
Name: Ferretería donde compra, dtype: int64

In [48]:
df.groupby(['Zona / Localidad', 'Ferretería donde compra']).size()

Zona / Localidad    Ferretería donde compra
HAINA               FAUSTO / AXEL                      1
                    FERRETERIA FAUSTO                  6
                    FERRETERIA LA HACIENDA             3
                    TEO                                1
LAGUNAS DE NISIBON  FERRETERIA CASTILLO                2
LOS ALCARRIZOS      DE LEON RIVAS                      2
                    FERREBEGO                          1
SABANA IGLESIA      CENTRO FERRETERO SABANA IGLESIA    1
SAN JOSE DE OCOA    FERNANDEZ                          1
                    FERREFACIL                         5
                    FERRETERIA JUANA                   1
                    MARTINEZ PACHA                     1
SAN JUAN            FERRETERIA ARSENILIA               1
                    FERRETERIA HUMBERTO                2
dtype: int64

In [50]:
df['Marca usada al momento del abordaje'].value_counts(normalize=True) * 100

Marca usada al momento del abordaje
ARGOS           86.96
DOMICEM          6.52
CIBAO            2.17
SANTO DOMINGO    2.17
PANAM            2.17
Name: proportion, dtype: float64

In [53]:
df[df['Marca usada al momento del abordaje'] != 'ARGOS']['Zona / Localidad'].value_counts()

Zona / Localidad
LOS ALCARRIZOS        2
LAGUNAS DE NISIBON    2
SABANA IGLESIA        2
HAINA                 1
Name: count, dtype: int64

In [54]:
df.loc[df['Marca usada al momento del abordaje'] == 'ARGOS', 'Zona / Localidad'].unique()

array(['HAINA', 'LOS ALCARRIZOS', 'SAN JUAN ', 'SAN JOSE DE OCOA', 'AZUA'],
      dtype=object)

In [25]:
df.groupby(['¿Probó fundas Titan durante la visita?', 'Resultado de prueba en obra']).size().reset_index(name='frecuencias').sort_values(by='frecuencias', ascending=False)

,¿Probó fundas Titan durante la visita?,Resultado de prueba en obra,frecuencias
3,SI,POSITIVO,33
2,SI,NEUTRAL,4
0,NO,NO REALIZADA,2
1,SI,NEGATIVO,2

In [26]:
# Calcular conteos
conteos = df.groupby(['¿Probó fundas Titan durante la visita?', 'Resultado de prueba en obra']).size().reset_index(name='frecuencias')

# Calcular el total para obtener proporciones
total = conteos['frecuencias'].sum()

# Crear columna con proporción decimal (frecuencia / total)
conteos['proporcion'] = (conteos['frecuencias'] / total).round(2)  # redondeado a 2 decimales

# Ordenar por proporción descendente
resultado = conteos.sort_values(by='proporcion', ascending=False)

resultado

,¿Probó fundas Titan durante la visita?,Resultado de prueba en obra,frecuencias,proporcion
3,SI,POSITIVO,33,0.80
2,SI,NEUTRAL,4,0.10
0,NO,NO REALIZADA,2,0.05
1,SI,NEGATIVO,2,0.05

In [27]:
df['¿Aceptó volver a probar Titan?'].value_counts(normalize=True)

¿Aceptó volver a probar Titan?
NO   0.71
SI   0.29
Name: proportion, dtype: float64

In [28]:
df[df['Resultado de prueba en obra'] != 'POSITIVO']

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,Motivo de inconformidad con Titan,¿Probó fundas Titan durante la visita?,Cantidad de fundas dejadas para prueba,Resultado de prueba en obra,Comentarios técnicos / percepción del maestro,¿Aceptó volver a probar Titan?,¿Se registró en Conéctate Maestro?,¿Se aplicó bono?,Fecha de redención de bono,# de fundas compradas luego del abordaje,¿Ha influenciado a otro maestro?,Nombre del maestro influenciado,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
1,2025-04-03,PRIMERA VISITA,HAINA,FREDDY PEREZ,YANIRIS,Amauris Pichardo,8297866997.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,SI,18.42,-70.03
4,2025-03-15,PRIMERA VISITA,HAINA,RAFAEL PIMENTEL,YANIRIS,Amauris Pichardo,8492138214.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,10.00,NaN,NaN,NaN,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,SI,18.43,-70.02
5,2025-04-07,PRIMERA VISITA,HAINA,CANDIDO MARRERO,YANIRIS,Amauris Pichardo,8093340743.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,8.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,RESISTENCIA,NO,TEO,NaN,SI,18.43,-70.03
7,2025-05-16,PRIMERA VISITA,LOS ALCARRIZOS,FRANDELY,PAMELA,Amauris Pichardo,8496304247.00,JUAN CARLOS,REFERIDO POR COMERCIAL,CIBAO,RESISTENCIA,SI,2.00,NEUTRAL,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,COLOR,SI,FERREBEGO,NaN,SI,18.52,-70.03
8,2025-05-19,PRIMERA VISITA,LOS ALCARRIZOS,JOSE MANUEL,PAMELA,Amauris Pichardo,8095020840.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,3.00,NEUTRAL,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE LEON RIVAS,NaN,SI,18.52,-70.04
9,2025-05-19,PRIMERA VISITA,LOS ALCARRIZOS,LUCA BERNARD,PAMELA,Amauris Pichardo,NaN,JUAN CARLOS,IDENTIFICADO EN OBRA,NaN,COLOR,SI,4.00,NEUTRAL,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE LEON RIVAS,NaN,SI,18.53,-70.05
10,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,JULIAN,SURI,Ricardo Rodriguez,8297856515.00,JUAN CARLOS,REFERIDO POR COMERCIAL,SANTO DOMINGO,RESISTENCIA,SI,5.00,NEGATIVO,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,COLOR,NO,FERRETERIA CASTILLO,NaN,SI,18.84,-68.67
11,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,"JOSE CESAREO ""PAJARITO""",SURI,Ricardo Rodriguez,8095149545.00,JUAN CARLOS,REFERIDO POR COMERCIAL,PANAM,COLOR,NO,NaN,NO REALIZADA,POCA RESISTENCIA,NO,NO,NO,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA CASTILLO,ADEMAS DE LA SITUACION CON EL COLOR DEL PRODUC...,SI,18.83,-68.67
14,2025-05-23,PRIMERA VISITA,SAN JUAN,CHAN,LUIS,Amauris Pichardo,8293270329.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,RESISTENCIA,SI,6.00,NEGATIVO,NO TIENE LA RESISTENCIA ESPERADA Y MENOR RENDI...,NO,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,SI,RENDIMIENTO,SI,FERRETERIA HUMBERTO,NaN,SI,18.75,-71.19
16,2025-04-24,PRIMERA VISITA,SABANA IGLESIA,MERISIER,MERCEDES,Siquio Salazar,NaN,JUAN CARLOS,REFERIDO POR COMERCIAL,DOMICEM,RESISTENCIA,NO,NaN,NO REALIZADA,BAJO RENDIMIENTO,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,19.33,-70.76
39,2025-04-26,PRIMERA VISITA,AZUA,WILLIAM MEDRANO,RAQUEL,Amauris Pichardo,8097102794.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,NO,NaN,NaN,POCA RESISTENCIA,NaN,SI,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.45,-70.75
40,2025-04-26,PRIMERA VISITA,AZUA,ESQUIA ARVELO,RAQUEL,Amauris Pichardo,8292090022.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,NO,NaN,NaN,BAJO RENDIMIENTO,NaN,SI,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.46,-70.73
41,2025-04-26,PRIMERA VISITA,AZUA,WILLY URBAEZ,RAQUEL,Amauris Pichardo,8292940281.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,NO,NaN,NaN,MAL COLOR,NaN,SI,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.46,-70.75
44,2025-04-26,PRIMERA VISITA,AZUA,NICOLAS ROSARIO,RAQUEL,Amauris Pichardo,8292964226.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,NEUTRAL,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.46,-70.73

In [29]:
df[df['¿Se aplicó bono?'] == 'SI']

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,Motivo de inconformidad con Titan,¿Probó fundas Titan durante la visita?,Cantidad de fundas dejadas para prueba,Resultado de prueba en obra,Comentarios técnicos / percepción del maestro,¿Aceptó volver a probar Titan?,¿Se registró en Conéctate Maestro?,¿Se aplicó bono?,Fecha de redención de bono,# de fundas compradas luego del abordaje,¿Ha influenciado a otro maestro?,Nombre del maestro influenciado,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
34,2025-04-15,SEGUIMIENTO,HAINA,RAFAEL PIMENTEL,YANIRIS,Amauris Pichardo,8492138214.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,4.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
35,2025-06-27,PRIMERA VISITA,HAINA,DARIO JIMENEZ,YANIRIS,Amauris Pichardo,8099530357.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,9.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.41,-70.04
36,2025-06-27,PRIMERA VISITA,HAINA,RAMON ALVAREZ,YANIRIS,Amauris Pichardo,8292974492.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA LA HACIENDA,NaN,NO,18.42,-70.04
37,2025-06-27,PRIMERA VISITA,HAINA,WLIKIN DE OLEO,YANIRIS,Amauris Pichardo,8093996275.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.41,-70.04
38,2025-06-27,PRIMERA VISITA,HAINA,ROBERTO JAVIER,YANIRIS,Amauris Pichardo,8098618672.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.41,-70.03
42,2025-04-26,PRIMERA VISITA,AZUA,JOSE MANUEL,RAQUEL,Amauris Pichardo,8292165217.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.44,-70.73
43,2025-04-26,PRIMERA VISITA,AZUA,RADAMES ORTIZ,RAQUEL,Amauris Pichardo,8096759701.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.45,-70.71
44,2025-04-26,PRIMERA VISITA,AZUA,NICOLAS ROSARIO,RAQUEL,Amauris Pichardo,8292964226.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,COLOR,SI,5.00,NEUTRAL,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.46,-70.73
45,2025-04-26,PRIMERA VISITA,AZUA,RAFAEL MERO,RAQUEL,Amauris Pichardo,8494239611.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,DISPONIBILIDAD,SI,5.00,POSITIVO,NaN,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.44,-70.74
46,2025-04-26,PRIMERA VISITA,AZUA,JOSE DEL CARMEN,RAQUEL,Amauris Pichardo,NaN,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,5.00,POSITIVO,NaN,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.45,-70.75

In [30]:
df[df['¿Ha influenciado a otro maestro?'] == 'SI']

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,Motivo de inconformidad con Titan,¿Probó fundas Titan durante la visita?,Cantidad de fundas dejadas para prueba,Resultado de prueba en obra,Comentarios técnicos / percepción del maestro,¿Aceptó volver a probar Titan?,¿Se registró en Conéctate Maestro?,¿Se aplicó bono?,Fecha de redención de bono,# de fundas compradas luego del abordaje,¿Ha influenciado a otro maestro?,Nombre del maestro influenciado,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
15,2025-04-24,PRIMERA VISITA,SABANA IGLESIA,IGNACIO RODRIGUEZ,MERCEDES,Siquio Salazar,8097617532.00,JUAN CARLOS,REFERIDO POR COMERCIAL,DOMICEM,COLOR,SI,5.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,536.00,SI,LEO,8096717580.00,50.00,NaN,NaN,NaN,CENTRO FERRETERO SABANA IGLESIA,NaN,SI,19.29,-70.74
21,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,LECLES ELIUS,RAQUEL,Amauris Pichardo,8094977171.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,JUAN PEREZ,NaN,15.00,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.53,-70.51
22,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FRANCIS FILOGENE,RAQUEL,Amauris Pichardo,8298919912.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,MANUEL,NaN,80.00,NaN,NaN,NaN,FERNANDEZ,NaN,SI,18.55,-70.51
23,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FERNANDO PETTER,RAQUEL,Amauris Pichardo,8296335597.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,IVAN,NaN,125.00,NaN,NaN,NaN,FERRETERIA JUANA,NaN,SI,18.54,-70.51
24,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,PITTER ABERA,RAQUEL,Amauris Pichardo,8494927897.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,RESISTENCIA,SI,9.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,NaN,SI,CRISTIAN,NaN,85.00,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.59,-70.50
25,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,JESUS PINEDA,RAQUEL,Amauris Pichardo,8294260508.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,7.00,POSITIVO,NaN,NaN,NaN,NaN,NaN,10.00,SI,JOSE,NaN,60.00,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN

In [31]:
df[df['¿Reportó alguna queja?'] == 'SI']

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,Motivo de inconformidad con Titan,¿Probó fundas Titan durante la visita?,Cantidad de fundas dejadas para prueba,Resultado de prueba en obra,Comentarios técnicos / percepción del maestro,¿Aceptó volver a probar Titan?,¿Se registró en Conéctate Maestro?,¿Se aplicó bono?,Fecha de redención de bono,# de fundas compradas luego del abordaje,¿Ha influenciado a otro maestro?,Nombre del maestro influenciado,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
0,2025-04-01,PRIMERA VISITA,HAINA,ROBERT PEÑA,YANIRIS,Amauris Pichardo,8292757981.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,10.00,POSITIVO,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,RENDIMIENTO,SI,FERRETERIA FAUSTO,NaN,SI,18.41,-70.03
2,2025-05-02,PRIMERA VISITA,HAINA,ANTONIO CASTILLO,YANIRIS,Amauris Pichardo,8297854594.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,3.00,POSITIVO,NaN,NaN,SI,NaN,NaN,250.00,NaN,NaN,NaN,NaN,SI,COLOR,SI,FERRETERIA LA HACIENDA,NaN,SI,18.43,-70.02
5,2025-04-07,PRIMERA VISITA,HAINA,CANDIDO MARRERO,YANIRIS,Amauris Pichardo,8093340743.00,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,COLOR,SI,8.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,RESISTENCIA,NO,TEO,NaN,SI,18.43,-70.03
7,2025-05-16,PRIMERA VISITA,LOS ALCARRIZOS,FRANDELY,PAMELA,Amauris Pichardo,8496304247.00,JUAN CARLOS,REFERIDO POR COMERCIAL,CIBAO,RESISTENCIA,SI,2.00,NEUTRAL,NaN,SI,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,COLOR,SI,FERREBEGO,NaN,SI,18.52,-70.03
10,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,JULIAN,SURI,Ricardo Rodriguez,8297856515.00,JUAN CARLOS,REFERIDO POR COMERCIAL,SANTO DOMINGO,RESISTENCIA,SI,5.00,NEGATIVO,NaN,NO,SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,COLOR,NO,FERRETERIA CASTILLO,NaN,SI,18.84,-68.67
14,2025-05-23,PRIMERA VISITA,SAN JUAN,CHAN,LUIS,Amauris Pichardo,8293270329.00,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,RESISTENCIA,SI,6.00,NEGATIVO,NO TIENE LA RESISTENCIA ESPERADA Y MENOR RENDI...,NO,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,SI,RENDIMIENTO,SI,FERRETERIA HUMBERTO,NaN,SI,18.75,-71.19

In [32]:
df[df['Comentarios adicionales o sugerencias'].notna()]

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,Motivo de inconformidad con Titan,¿Probó fundas Titan durante la visita?,Cantidad de fundas dejadas para prueba,Resultado de prueba en obra,Comentarios técnicos / percepción del maestro,¿Aceptó volver a probar Titan?,¿Se registró en Conéctate Maestro?,¿Se aplicó bono?,Fecha de redención de bono,# de fundas compradas luego del abordaje,¿Ha influenciado a otro maestro?,Nombre del maestro influenciado,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
11,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,"JOSE CESAREO ""PAJARITO""",SURI,Ricardo Rodriguez,8095149545.00,JUAN CARLOS,REFERIDO POR COMERCIAL,PANAM,COLOR,NO,NaN,NO REALIZADA,POCA RESISTENCIA,NO,NO,NO,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,FERRETERIA CASTILLO,ADEMAS DE LA SITUACION CON EL COLOR DEL PRODUC...,SI,18.83,-68.67